### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by sfahadshahzad** [freehand-dev/FFMpegEncoder#1]
Hi,

I am getting error when executing application.

$Env:EnvironmentName=Production
$Env:ApplicationName=FFMpegEncoder
$Env:ContentRootPath=C:\Users\admin\Desktop\FFMpegEncoder-main\%ProgramData%\FreeHand\FFMpegEncoder\bin\
WorkingDirectory=C:\ProgramData\FreeHand\FFMpegEncoder
CurrentDirectory=C:\Users\admin\Desktop\FFMpegEncoder-main\%ProgramData%\FreeHand\FFMpegEncoder\bin
Config=none
ServiceName=FreeHand FFMpegEncoder; InstanceName=Default
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker running at: 11/03/2022 19:32:02 +05:00
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Exception: Failed create FFMpeg Arguments Processor System.Exception
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\admin\Desktop\FFMpegEncoder-main\%ProgramData%\FreeHand\FFMpegEncoder\bin\
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Exception: Failed create FFMpeg Arguments Processor System.Exception
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Exception: Failed create FFMpeg Arguments Processor System.Exception
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
      FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]

Regards,

Fahad

**Comment by freehand-dev** [comment]
Hi,

You need to put the default config file (default.json) to C:\ProgramData\FreeHand\FFMpegEncoder and extract ffmpeg-bin to C:\ProgramData\FreeHand\FFMpegEncoder\bin\ffmpeg-bin

***@***.***

***@***.***


Or set config via arguments FFMpegEncoder.exe -local-config c:\some-path\some-config.json

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Thursday, November 3, 2022 4:34 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [freehand-dev/FFMpegEncoder] getting error (Issue #1)


Hi,

I am getting error when executing application.

$Env:EnvironmentName=Production
$Env:ApplicationName=FFMpegEncoder
$Env:ContentRootPath=C:\Users\admin\Desktop\FFMpegEncoder-main%ProgramData%\FreeHand\FFMpegEncoder\bin
WorkingDirectory=C:\ProgramData\FreeHand\FFMpegEncoder
CurrentDirectory=C:\Users\admin\Desktop\FFMpegEncoder-main%ProgramData%\FreeHand\FFMpegEncoder\bin
Config=none
ServiceName=FreeHand FFMpegEncoder; InstanceName=Default
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker running at: 11/03/2022 19:32:02 +05:00
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Exception: Failed create FFMpeg Arguments Processor System.Exception
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
Content root path: C:\Users\admin\Desktop\FFMpegEncoder-main%ProgramData%\FreeHand\FFMpegEncoder\bin
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Exception: Failed create FFMpeg Arguments Processor System.Exception
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Exception: Failed create FFMpeg Arguments Processor System.Exception
info: sdi2srt_ffmpeg.Services.FFMpegWorker[0]
FFMpegWorker.ProcessAsynchronously.Start
fail: sdi2srt_ffmpeg.Services.FFMpegWorker[0]

Regards,

Fahad

**Comment by sfahadshahzad** [comment]
Ok will try and update you.

Thanks

**Comment by sfahadshahzad** [comment]
yes it worked.

Thanks
