### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by sfahadshahzad** [freehand-dev/FFMpegEncoder#2]
Hi,

I tried to edit json file for audio channels but not getting audio. Getting audio from sdi embedded signal but the source signal has only  2 channels.

[decklink @ 0000021faa79c1c0] Autodetected the input mode
[decklink @ 0000021faa79c1c0] Found Decklink mode 720 x 576 with rate 25.00(i)
Input #0, decklink, from 'DeckLink Quad (4)':
  Duration: N/A, start: 0.000000, bitrate: 167424 kb/s
  Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
  Stream #0:1: Video: rawvideo (UYVY / 0x59565955), uyvy422(top first), 720x576, 165888 kb/s, 25 fps, 25 tbr, 1000k tbn

how can I define incoming audio in the json file.

Fahad

**Comment by freehand-dev** [comment]
Hi,
Sample config in attached.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Thursday, November 3, 2022 11:24 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [freehand-dev/FFMpegEncoder] No Audio (Issue #2)


Hi,

I tried to edit json file for audio channels but not getting audio. Getting audio from sdi embedded signal but the source signal has only 2 channels.

[decklink @ 0000021faa79c1c0] Autodetected the input mode
[decklink @ 0000021faa79c1c0] Found Decklink mode 720 x 576 with rate 25.00(i)
Input #0, decklink, from 'DeckLink Quad (4)':
Duration: N/A, start: 0.000000, bitrate: 167424 kb/s
Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
Stream #0:1: Video: rawvideo (UYVY / 0x59565955), uyvy422(top first), 720x576, 165888 kb/s, 25 fps, 25 tbr, 1000k tbn

how can I define incoming audio in the json file.

Fahad

**Comment by freehand-dev** [comment]
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
    "ffmpeg": {
	  "LogLevel": 40,
	  "Raw": "",
      "Input": {
        "Device": "decklink",
        "Name": "DeckLink Duo (4)",
        "Channels": 8,
        "Format": "Hi50",
        "RawFormat": "uyvy422",
        "VideoInput": "sdi",
        "AudioInput": "embedded",
        "DrawBars": false,
        "QueueSize": 1073741824
      },
	  "FilterComplex": [
		"[0:v]yadif"
      ],
      "Maps": [
        "0:v",
        "0:a",
      ],
      "Encoders": [
        {
          "Codec": "libx264",
          "Bitrate": 8000,
          "Preset": "faster",
		  "Profile": "high",
		  "Level": "4.0",
		  "Flags": [
			  "+ilme",
			  "+ildct",
			  "+cgop"
		  ],
		  "CustomArguments": [
			{ "Name" : "minrate", 		"Value": "8000k" },
			{ "Name" : "maxrate", 		"Value": "8000k" },
			{ "Name" : "bufsize", 		"Value": "700k" },
			{ "Name" : "pix_fmt", 		"Value": "yuv420p" },
			{ "Name" : "aspect", 		"Value": "16:9" },
			{ "Name" : "x264-params", 	"Value": "nal-hrd=cbr" },
			{ "Name" : "top", 			"Value": 1 }
		  ],
          "CustomArguments1": [
			{ "Name" : "minrate", 		"Value": "8000k" },
			{ "Name" : "maxrate", 		"Value": "8000k" },
			{ "Name" : "bufsize", 		"Value": "700k" },
			{ "Name" : "pix_fmt", 		"Value": "yuv420p" },
			{ "Name" : "aspect", 		"Value": "16:9" },
			{ "Name" : "r", 			"Value": 25 },
			{ "Name" : "x264-params", 	"Value": "force-cfr=1:nal-hrd=cbr" },
			{ "Name" : "g", 			"Value": 250 },
			{ "Name" : "top", 			"Value": 1 },
			{ "Name" : "trellis", 		"Value": 1 },
			{ "Name" : "me_method", 	"Value": "umh" },
			{ "Name" : "sc_threshold", 	"Value": 40 },
			{ "Name" : "keyint_min", 	"Value": 25 },
			{ "Name" : "bf", 			"Value": 16 },
			{ "Name" : "qmin", 			"Value": 10 },
			{ "Name" : "qmax", 			"Value": 51 },
			{ "Name" : "qdiff", 		"Value": 4 }
          ],
		  "CustomArguments2": [
			{ "Name" : "minrate", 		"Value": "8000k" },
			{ "Name" : "maxrate", 		"Value": "8000k" },
			{ "Name" : "bufsize", 		"Value": "700k" },
			{ "Name" : "pix_fmt", 		"Value": "yuv420p" },
			{ "Name" : "aspect", 		"Value": "16:9" },
			{ "Name" : "x264-params", 	"Value": "nal-hrd=cbr" },
			{ "Name" : "g", 			"Value": 250 },
			{ "Name" : "top", 			"Value": 1 },
			{ "Name" : "trellis", 		"Value": 1 },
			{ "Name" : "me_method", 	"Value": "umh" },
			{ "Name" : "sc_threshold", 	"Value": 40 },
			{ "Name" : "keyint_min", 	"Value": 25 },
			{ "Name" : "bf", 			"Value": 16 },
			{ "Name" : "qmin", 			"Value": 10 },
			{ "Name" : "qmax", 			"Value": 51 },
			{ "Name" : "qdiff", 		"Value": 4 }
          ]
        },
        {
          "Codec": "libfdk_aac",
          "Bitrate": 192,
          "CustomArguments": [

          ]
        }
      ],
      "BitstreamFilter": {
        "video": [ "h264_mp4toannexb" ],
        "audio": []
      },
      "GlobalOptions": [
	  	{ "Name" : "flush_packets", "Value": 0 },
		{ "Name" : "rtbufsize", 	"Value": "2000M" }
      ],
      "Muxer": {
        "mpegts": {
		  "TransportStreamId": 1,
		  "OriginalNetworkId": 1,
		  "ServiceId": 1,		  
          "StartPid": 336,
		  "PmtStartPid": 4096,
          "PcrPeriod": 20,
          "PatPeriod": "0.10",
          "SdtPeriod": "0.25",
		  "NitPeriod": "0.5",
		  "MuxRate": 9000,
          "Metadata": {
            "service_provider": "ES",
            "service_name": "OBVan",
            "title": "BabyBird"
          },
          "Flags": [
            "+pat_pmt_at_frames",
            "+system_b",
			"+nit"
          ],
          "Output": {
            "Protocol": "srt",
            "Address": "46.164.131.218",
            "Port": 9102,
			"Options": [
				{ "Name" : "ipttl", 		"Value": 15 },
				{ "Name" : "latency", 		"Value": 3000 },	
				{ "Name" : "mode", 			"Value": "caller" },
				{ "Name" : "payload_size", 	"Value": 1456 },
				{ "Name" : "transtype", 	"Value": "live" }					
			]
          },
		  "Output1": {
            "Protocol": "udp",
            "Address": "225.0.0.1",
            "Port": 1234,
			"Options": [
				{ "Name" : "pkt_size", "Value": 1316 },
				{ "Name" : "ttl", 	"Value": 15 },
				{ "Name" : "localaddr", 	"Value": "10.10.201.201" }
			]
          }
        }
      }
    }
}
