### ISSUE TITLE
SRT Stats

### ISSUE THREAD

**Issue by sfahadshahzad** [freehand-dev/FFMpegEncoder#3]
Hi,

It would be great if you can log all srt statistics in json file.

Regards,

Fahad

**Comment by freehand-dev** [comment]
Hi,

I am planning to parse FFmpeg output and add:
- OpenTelemetry Logging for mpegts, srt, decklink modules 
- OpenTelemetry Metrics for Fmpeg progress.

Regards,

**Comment by sfahadshahzad** [comment]
Hi,

Can you please tell me how I can enable logging ?

Regards,

Fahad

**Comment by freehand-dev** [comment]
Hi,

I will soon update the repository, the new version will add logging to the file.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
