### ISSUE TITLE
Multiplexer service

### ISSUE THREAD

**Issue by sfahadshahzad** [freehand-dev/FFMpegEncoder#4]
Hi,

I am running three encoding services and looking to mux all SPTS into single multiplexed MPTS stream.

How I can do it by creating another service.

Regards,

Fahad

**Comment by freehand-dev** [comment]
Hi

For run multi-instance application, you can use arguments for config file
`-local-config c:\test\instance2.json`

or install service with InstanceName
`--name service2`

```
sc create FreeHandFFMpegEncoderSvc_Default 
binPath= "%ProgramData%\FreeHand\FFMpegEncoder\bin\FFMpegEncoder.exe --name service2"
DisplayName= "FreeHand FFMpegEncoder (Service2)" 
start= auto
description= "FreeHand FFMpegEncoder (Service2)"
```

config file name and location is `%ProgramData%\FreeHand\FFMpegEncoder\service2.json`

Regards,

**Comment by sfahadshahzad** [comment]
Hi,

I am already running multiple services as you mentioned above.

Need to know how I can merge all services into one mux stream.

Fahad

**Comment by freehand-dev** [comment]
Hi,

Try [TSDuck ](https://tsduck.io/)to multiplex some SPTS to one MPTS stream.
